obj-$(CONFIG_IVEIA_EVENTS)			+= main.o
obj-$(CONFIG_MACH_IV_ATLAS_I_LPE)	+= board-atlas-i-lpe.o
obj-$(CONFIG_IVEIA_TITANV5)			+= board-titan-v5.o
obj-$(CONFIG_IVEIA_TITAN_PPCX)		+= board-titan-ppcx.o
obj-$(CONFIG_MACH_IV_ATLAS_I_Z7E)	+= board-atlas-i-z7e.o
obj-$(CONFIG_ARCH_IV_ATLAS_II_Z8)   += board-atlas-ii-z8.o
