#!/bin/sh

# /var must be writeable.  Copy its contents to a tmpfs on top of it.
mkdir /tmp/var
mount -t tmpfs -o size=256k tmpfs /tmp/var
if ! cp -af /var/* /tmp/var ; then
    echo "Failed copying /var to read/write tmpfs.  Perhaps /var is too big?"
fi
mount --move /tmp/var /var
